export default {
  grid: {
    container: '130rem',
    gutter: '3.2rem',
  },
  border: {
    radius: '0.8rem',
  },
  font: {
    family:
      "Poppins, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif",
    light: 300,
    normal: 400,
    bold: 600,
    sizes: {
      xsmall: '1.2rem',
      small: '1.4rem',
      medium: '1.6rem',
      large: '1.8rem',
      xlarge: '2.0rem',
      xxlarge: '2.8rem',
    },
  },
  colors: {
    primary: '#2a9d8f',
    secondary: '#e76f51',
    mainBg: '#264653',
    white: '#FAFAFA',
    black: '#030517',
    lightGray: '#EAEAEA',
    gray: '#8F8F8F',
    darkGray: '#2E2F42',
  },
  typeBg: {
    normal: '#cdcd',
    grass: '#52b788',
    fire: '#e76f51',
    water: '#4361ee',
    fighting: '#6f1d1b',
    flying: '#bde0fe',
    poison: '#841db6',
    ground: '#d2bd77',
    rock: '#a77f66',
    bug: '#bfd200',
    ghost: '#380054',
    electric: '#eeef20',
    psychic: '#9984d4',
    ice: '#ade8f4',
    dragon: '#8093f1',
    dark: '#352208',
    steel: '#adb5bd',
    fairy: '#caa8f5',
  },
  spacing: {
    xxsmall: '0.8rem',
    xsmall: '1.6rem',
    small: '2.4rem',
    medium: '3.2rem',
    large: '4.0rem',
    xlarge: '4.8rem',
    xxlarge: '5.6rem',
    xxxlarge: '9.6rem',
  },
  layers: {
    base: 10,
    menu: 20,
    overlay: 30,
    modal: 40,
    alwaysOnTop: 50,
  },
};
